---
- name: generate ironic json file
  hosts: all
  gather_facts: false
  tasks:
  - name: generate json file
    template:
      src: ironic_hosts.j2
      dest: ironic_hosts.json
      mode: '0644'
    delegate_to: localhost
    run_once: True

- name: generate config user file
  hosts: all
  gather_facts: false
  tasks:
  - name: generate json file
    template:
      src: config_user.j2
      dest: config_$KNIUSER.sh
      mode: '0755'
    delegate_to: localhost
    run_once: True

- name: generate install-config.yaml file
  hosts: all
  gather_facts: false
  tasks:
  - name: generate yaml file
    template:
      src: install-config.j2
      dest: install-config.yaml
      mode: '0644'
    delegate_to: localhost
    run_once: True
    
- name: generate host patch json
  hosts: masters
  gather_facts: false
  tasks:

  - name: pull in hw profile
    set_fact:
      hardware_json: "{{ lookup('file', '{{ inventory_hostname }}.hwprofile.json') | from_json }}"

  - name: make_host_patch_json with jinga2
    template:
      src: host_patch.j2
      dest: host_patch.{{ inventory_hostname }}.json
      mode: '0755'
    delegate_to: localhost
